name: ðŸš€ Deploy Backend to GoViral
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸ“‚ Sync Files
    runs-on: ubuntu-latest
    # Added environment variables to the job level
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“¤ FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./public_html/api/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            README.md